<?php
defined('ABSPATH') || exit;

add_action('acf/init', 'dalili_register_acf_fields');

function dalili_register_acf_fields() {
    if (!function_exists('acf_add_local_field_group')) return;

    // ─── Station Fields ─────────────────────────────────────────
    acf_add_local_field_group([
        'key'    => 'group_dalili_station',
        'title'  => 'بيانات المحطة',
        'fields' => [
            [
                'key'          => 'field_station_id',
                'label'        => 'معرّف المحطة',
                'name'         => 'station_id',
                'type'         => 'text',
                'required'     => 1,
                'instructions' => 'مثال: st-01  (يُستخدم في الكود للربط مع الخريطة)',
                'placeholder'  => 'st-01',
            ],
            [
                'key'          => 'field_station_name_ar',
                'label'        => 'الاسم بالعربية',
                'name'         => 'name_ar',
                'type'         => 'text',
                'required'     => 1,
            ],
            [
                'key'   => 'field_station_name_en',
                'label' => 'الاسم بالإنجليزية',
                'name'  => 'name_en',
                'type'  => 'text',
            ],
            [
                'key'          => 'field_station_svg_x',
                'label'        => 'موضع X على الخريطة',
                'name'         => 'svg_x',
                'type'         => 'number',
                'required'     => 1,
                'min'          => 0,
                'max'          => 2250,
                'step'         => 1,
                'instructions' => 'الإحداثي الأفقي في SVG (0–2250)',
            ],
            [
                'key'          => 'field_station_svg_y',
                'label'        => 'موضع Y على الخريطة',
                'name'         => 'svg_y',
                'type'         => 'number',
                'required'     => 1,
                'min'          => 0,
                'max'          => 1800,
                'step'         => 1,
                'instructions' => 'الإحداثي الرأسي في SVG (0–1800)',
            ],
            [
                'key'           => 'field_station_status',
                'label'         => 'حالة المحطة',
                'name'          => 'status',
                'type'          => 'select',
                'choices'       => [
                    'active'             => 'نشطة',
                    'inactive'           => 'غير نشطة',
                    'under_construction' => 'تحت الإنشاء',
                ],
                'default_value' => 'active',
                'required'      => 1,
            ],
            [
                'key'   => 'field_station_description_ar',
                'label' => 'وصف المحطة',
                'name'  => 'description_ar',
                'type'  => 'textarea',
                'rows'  => 2,
            ],
        ],
        'location' => [[['param' => 'post_type', 'operator' => '==', 'value' => 'dalili_station']]],
        'menu_order'            => 0,
        'position'              => 'normal',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
    ]);

    // ─── Transit Line Fields ────────────────────────────────────
    acf_add_local_field_group([
        'key'    => 'group_dalili_line',
        'title'  => 'بيانات خط النقل',
        'fields' => [
            [
                'key'          => 'field_line_id',
                'label'        => 'معرّف الخط',
                'name'         => 'line_id',
                'type'         => 'text',
                'required'     => 1,
                'instructions' => 'مثال: line-teal  (يُستخدم في الكود للربط مع المحطات)',
                'placeholder'  => 'line-teal',
            ],
            [
                'key'      => 'field_line_name_ar',
                'label'    => 'اسم الخط بالعربية',
                'name'     => 'name_ar',
                'type'     => 'text',
                'required' => 1,
            ],
            [
                'key'   => 'field_line_name_en',
                'label' => 'اسم الخط بالإنجليزية',
                'name'  => 'name_en',
                'type'  => 'text',
            ],
            [
                'key'           => 'field_line_color',
                'label'         => 'لون الخط',
                'name'          => 'line_color',
                'type'          => 'color_picker',
                'required'      => 1,
                'default_value' => '#3b82f6',
            ],
            [
                'key'           => 'field_line_status',
                'label'         => 'حالة الخط',
                'name'          => 'line_status',
                'type'          => 'select',
                'choices'       => [
                    'active'   => 'نشط',
                    'partial'  => 'جزئي',
                    'inactive' => 'متوقف',
                ],
                'default_value' => 'active',
                'required'      => 1,
            ],
            [
                'key'          => 'field_line_direction_label',
                'label'        => 'وصف الاتجاه',
                'name'         => 'direction_label',
                'type'         => 'text',
                'instructions' => 'مثال: ذهاب / إياب',
                'placeholder'  => 'ذهاب / إياب',
            ],
            [
                'key'   => 'field_line_description',
                'label' => 'وصف الخط',
                'name'  => 'line_description',
                'type'  => 'textarea',
                'rows'  => 2,
            ],
        ],
        'location' => [[['param' => 'post_type', 'operator' => '==', 'value' => 'dalili_line']]],
        'menu_order'            => 0,
        'position'              => 'normal',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
    ]);

    // ─── Line Stop Fields ───────────────────────────────────────
    // One record = one station on one line (ordered many-to-many join)
    acf_add_local_field_group([
        'key'    => 'group_dalili_stop',
        'title'  => 'بيانات نقطة التوقف',
        'fields' => [
            [
                'key'           => 'field_stop_line_ref',
                'label'         => 'الخط',
                'name'          => 'line_ref',
                'type'          => 'post_object',
                'post_type'     => ['dalili_line'],
                'return_format' => 'id',
                'allow_null'    => 0,
                'required'      => 1,
                'ui'            => 1,
            ],
            [
                'key'           => 'field_stop_station_ref',
                'label'         => 'المحطة',
                'name'          => 'station_ref',
                'type'          => 'post_object',
                'post_type'     => ['dalili_station'],
                'return_format' => 'id',
                'allow_null'    => 0,
                'required'      => 1,
                'ui'            => 1,
            ],
            [
                'key'          => 'field_stop_order',
                'label'        => 'ترتيب التوقف',
                'name'         => 'stop_order',
                'type'         => 'number',
                'required'     => 1,
                'min'          => 1,
                'step'         => 1,
                'instructions' => 'رقم التوقف في تسلسل الخط (1، 2، 3، …)',
            ],
            [
                'key'          => 'field_stop_direction',
                'label'        => 'الاتجاه',
                'name'         => 'stop_direction',
                'type'         => 'text',
                'instructions' => 'مثال: ذهاب، أو إياب، أو اتجاهان',
                'placeholder'  => 'ذهاب',
            ],
            [
                'key'   => 'field_stop_notes',
                'label' => 'ملاحظات',
                'name'  => 'stop_notes',
                'type'  => 'text',
            ],
        ],
        'location' => [[['param' => 'post_type', 'operator' => '==', 'value' => 'dalili_stop']]],
        'menu_order'            => 0,
        'position'              => 'normal',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
    ]);

    // ─── Alert Fields ───────────────────────────────────────────
    acf_add_local_field_group([
        'key'    => 'group_dalili_alert',
        'title'  => 'بيانات التنبيه',
        'fields' => [
            [
                'key'      => 'field_alert_title_ar',
                'label'    => 'عنوان التنبيه',
                'name'     => 'title_ar',
                'type'     => 'text',
                'required' => 1,
            ],
            [
                'key'   => 'field_alert_message_ar',
                'label' => 'نص التنبيه',
                'name'  => 'message_ar',
                'type'  => 'textarea',
                'rows'  => 3,
            ],
            [
                'key'           => 'field_alert_type',
                'label'         => 'نوع التنبيه',
                'name'          => 'alert_type',
                'type'          => 'select',
                'choices'       => [
                    'info'     => 'معلومة',
                    'warning'  => 'تحذير',
                    'critical' => 'حرج',
                ],
                'default_value' => 'info',
            ],
            [
                'key'           => 'field_alert_status',
                'label'         => 'حالة التنبيه',
                'name'          => 'alert_status',
                'type'          => 'select',
                'choices'       => [
                    'active'    => 'نشط',
                    'scheduled' => 'مجدول',
                    'expired'   => 'منتهي',
                ],
                'default_value' => 'active',
                'required'      => 1,
            ],
            [
                'key'        => 'field_alert_affected_line',
                'label'      => 'الخط المتأثر',
                'name'       => 'affected_line',
                'type'       => 'post_object',
                'post_type'  => ['dalili_line'],
                'return_format' => 'id',
                'allow_null' => 1,
                'ui'         => 1,
            ],
            [
                'key'        => 'field_alert_affected_station',
                'label'      => 'المحطة المتأثرة',
                'name'       => 'affected_station',
                'type'       => 'post_object',
                'post_type'  => ['dalili_station'],
                'return_format' => 'id',
                'allow_null' => 1,
                'ui'         => 1,
            ],
            [
                'key'          => 'field_alert_start_date',
                'label'        => 'تاريخ البدء',
                'name'         => 'start_date',
                'type'         => 'date_picker',
                'display_format' => 'd/m/Y',
                'return_format'  => 'Y-m-d',
                'first_day'      => 0,
            ],
            [
                'key'          => 'field_alert_end_date',
                'label'        => 'تاريخ الانتهاء',
                'name'         => 'end_date',
                'type'         => 'date_picker',
                'display_format' => 'd/m/Y',
                'return_format'  => 'Y-m-d',
                'first_day'      => 0,
            ],
        ],
        'location' => [[['param' => 'post_type', 'operator' => '==', 'value' => 'dalili_alert']]],
        'menu_order'            => 0,
        'position'              => 'normal',
        'label_placement'       => 'top',
        'instruction_placement' => 'label',
    ]);
}
